# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6fabeaa1573413d70da44d79b099f949ba6fdfb6727d613ff442f0b9a2db7858d6d8b2559375e1358298cc78e7eeae6cd9b7cfd68b672214565e02752d073ae

test:
  secret_key_base: f826c1c1ff920fa20de2726f773d90dc210bbefa977b1d6ec1ac73539f5b11c5c5bb41aaf62acd766a4840b585f81126c32770679e39b5951bcc91515a243329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
